language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: Pxqeif258krW/7m2ncPZXjwdL2tENIueaAiwMWuJ8XJD56ZVtiEykU8w4u8+5vlgmdLRDTs7z3L9eE3/mnzeKH5NUOpAL/1rWx4DhvEonDPOrJfuhDej1rTFYmA+tBjWWYHwYvV59aN19G70Lxv2Z8n56IwkgBThP1h/XNEl4heLnZyO1O7jGOgHqr/+Ldds5tfsxQrygYAHMxdkdEnM6oXaQ1P9FEJ8WBiURUmF3nEMnXOtRzpYHL3hHVXev31bQ7VvpGrKqCGlyJaHvk+u3PWuhsjO6+8SbnF/UWuiwwnQsPn/nj0GI0WZ38rrrl6LCnNmYd4PyxJBZo/A9NLFqvMeTfkoZlkwZwejGLaEr19eF48veyg2Cy1UMn8wcM3xs9xfeMq2fs3w3eXbBOrdg0JSY3WhFbPPfn3gPwM2hKBALJ3j5GN6bWzmt0glXis6XO7zH7C64Z7obONqjl7rY+2U9eJ9EUtqhXxjhb+6oHn6ga9JfGhg8NEiLn6tfrn4qFuNq67ADctteooUP/vtsRIB3yeihs0FSKcI4mWuOBD/Os2Ug5PenAMeNQUANOCgM2JjPD5y2tL/dVBXAYqwy6tNzntSdkhRamlxSKqXj7+2v/XS64vFSZq8hn8hLKLbgjgSvTBsP3ofIzfZ5pB6QZ0/rdMaFX4Ru+aTWwwLvCE=
before_install:
- chmod +x ./script/push-javadoc-to-gh-pages.sh
after_success:
- gradle javadoc
- "./script/push-javadoc-to-gh-pages.sh"
before_deploy:
- gradle jar
deploy:
  provider: releases
  api_key:
    secure: M6tMHWEPwk9cwP8qh8p8I+TDFw1ix7+vm6oNMp+4vgnqSei7eg7mymJ5LLZ3K5nujewte4u1w/DlIWgNW5OsejKiazk2wWCPMfRHAb26nOm58KySuZ6vSgkP2wpSFUq60ONR/Lv7kegPoqyNtKUwLtUaDBh3y+wacmmNZdYl/ufQgRrQiZr+deBgYU7Q7jcrkWx9angh+Uku7mRTLIuXMtw5xZVFcGZRGIhAK70Wwclq1FjnZ2XeBWulBBa5jEsiIyt1PdBXWaukyiYpyPLYBaMnbzAaCNSQI5gNm2/AhL4vYUKTc019OE2wHrPkPvGVAU+ES6m4/tRzWKEqyvgWc2LjxIJF5KHzLS254o/2XThvilAcjvoxXChlE3nsjppS9xdpqH83T7ukNwhi0d0kgsZpj519aNPDMyz77JUUyGsyLpOpoiZdV5crGdVZot0TRje24Wb5gmqC1Bx+tjEfCE9bJh2vygQEpQAONdMZfF+ierQqXgWXIc4uvEf2izFXQTmWaPvhz47yHZ8DRc3ntoKG4zcDtyQBHv1MPwE8G1axvypWtKZ7vR/b3RcmqdiejlOdEctu9z9KZ+pJfSmBj5cO2p1bQI5588A3iJhB1BKgJfSIhPWp/XDC9C2MW57ys5a4ujFkHDYeTl/lwe4KnCKhx2cx1wnhX6AATS4Rf/M=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    tags: true
    repo: eserial/eserial

addons:
  sonarcloud:
    organization: eserial-github
script:
- "./gradlew sonarqube"
